# Generated by Django 2.1.7 on 2019-03-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearten_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagePrompt',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='textPrompt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
