# Generated by Django 2.1.7 on 2019-03-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hearten_api', '0003_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='textPrompt',
        ),
    ]
